server:
  port: 8100
spring:
  application:
    name: consumereureka
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
