server:
  port: 8002

spring:
  application:
    name: providerconsul8002

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}

