server:
  port: 8003

spring:
  application:
    name: providerfeign8003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/  #要注册到的注册中心地址
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: providerfeign8003
info:
  app.name: kuangshen-springcloud
  company.name: blog.kuangstudy.com
