server:
  port: 3344
spring:
  application:
    name: configcenter3344
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lu_jun_jieljj/springcloud-config.git
          #搜索目录
          search-paths: springcloud-config
          default-label: master
#      label: master
      #读取分支
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

