spring:
  application:
    name: providereureka
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  zipkin:
      base-url: http://localhost:9411
  sleuth:
      sampler:
      #采样率值介于0到1之间，1则表示全部采集
        probability: 1